language: python
sudo: false
cache: pip
matrix:
  include:
    - env: TOXENV=flake8-py27
      python: 2.7
    - env: TOXENV=flake8-py36
      python: 3.6
    - env: TOXENV=readme-py27
      python: 2.7
    - env: TOXENV=py27-dj18
      python: 2.7
    - env: TOXENV=py27-dj110
      python: 2.7
    - env: TOXENV=py27-dj111
      python: 2.7
    - env: TOXENV=py34-dj18
      python: 3.4
    - env: TOXENV=py34-dj110
      python: 3.4
    - env: TOXENV=py34-dj111
      python: 3.4
    - env: TOXENV=py35-dj18
      python: 3.5
    - env: TOXENV=py35-dj110
      python: 3.5
    - env: TOXENV=py35-dj111
      python: 3.5
    - env: TOXENV=py36-dj18
      python: 3.6
    - env: TOXENV=py36-dj110
      python: 3.6
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=pypy-dj18
      python: pypy
    - env: TOXENV=pypy-dj110
      python: pypy
    - env: TOXENV=pypy-dj111
      python: pypy
    - env: TOXENV=py34-dj20
      python: 3.4
    - env: TOXENV=py34-djmaster
      python: 3.4
    - env: TOXENV=py35-dj20
      python: 3.5
    - env: TOXENV=py35-djmaster
      python: 3.5
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=py36-djmaster
      python: 3.6
  allow_failures:
    - env: TOXENV=py34-dj20
      python: 3.4
    - env: TOXENV=py35-dj20
      python: 3.5
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=py34-djmaster
      python: 3.4
    - env: TOXENV=py35-djmaster
      python: 3.5
    - env: TOXENV=py36-djmaster
      python: 3.6
install:
  - pip install tox
script: tox -v
after_success:
  - pip install codecov
  - codecov --required -X gcov --flags ${TOXENV//-/ }
  - coverage report -m
branches:
  except: templates/1.5.x templates/1.6.x
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: Oq6xiBtbip8+0U8t1WvDcUt1tX6imQeaHXvB+bqh2eU+RYntz8UWl9UOxfQEV4ghssX1zEKeOZzpYohj+oEi5b8oJo3H8pcbJIdK6rTNJEjQpDGSSjI3I1pHlflAJCDhPlGIgZYVPlY0dWK50l86hL+Y7QzLXjgsVCqlTCCtDfA=
  on:
    tags: true
    repo: jazzband/django-configurations
    condition: "$TOXENV = py36-dj111"
