language: python
sudo: false
cache: pip
matrix:
  include:
  - env: TOXENV=readme-py27
    python: 2.7
  - env: TOXENV=py27-dj111-coverage
    python: 2.7
  - env: TOXENV=py35-dj111-coverage
    python: 3.5
  - env: TOXENV=py36-dj111-coverage
    python: 3.6
  - env: TOXENV=pypy-dj111-coverage
    python: pypy
    python: 3.5
  - env: TOXENV=py35-djmaster-coverage
    python: 3.5
  - env: TOXENV=py36-dj20-coverage
    python: 3.6
  - env: TOXENV=py36-dj21-coverage
    python: 3.6
  - env: TOXENV=py36-djmaster-coverage
    python: 3.6
  - env: TOXENV=py37-dj20-coverage
    python: 3.7
    dist: xenial
    sudo: true
  - env: TOXENV=py37-dj21-coverage
    python: 3.7
    dist: xenial
    sudo: true
  - env: TOXENV=py37-djmaster-coverage
    python: 3.7
    dist: xenial
    sudo: true
  - env: TOXENV=py38-dj22-coverage
    python: 3.8
    dist: xenial
    sudo: true
  - env: TOXENV=py38-dj30-coverage
    python: 3.8
    dist: xenial
    sudo: true
  allow_failures:
  - env: TOXENV=py35-djmaster-coverage
    python: 3.5
  - env: TOXENV=py36-djmaster-coverage
    python: 3.6
  - env: TOXENV=py37-djmaster-coverage
    python: 3.7
  - env: TOXENV=py38-djmaster-coverage
    python: 3.8
install:
- pip install tox
script: tox -v
after_success:
- |
  if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
    pip install codecov
    coverage xml
    codecov --required -X gcov fix pycov -f coverage.xml --flags ${TOXENV//-/ }
  fi
branches:
  except: templates/1.5.x templates/1.6.x
deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/django-configurations/upload
  distributions: sdist bdist_wheel
  password:
    secure: LuserSjUTGSsls9zrvck/FbfL+gFpNU/ywOQ/67ufEbbpGCeDBEgxDzgb0acfHNk8wlAkaPvaAejQBFtcUulhdNT/g0NsmaEAjd6HhCGM+FRJAnYFaj33Js6C+N2tX5wznL7uCBxqgtaaH0hf6ucqC8OXqwoCVGgdxAEnUlC/fY=
  on:
    tags: true
    repo: jazzband/django-configurations
    condition: "$TOXENV = py36-dj111"
